name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 autoflake
        # Skip dep install for now.
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: (use make format/lint locally to fix) format and lint
      run: |
        make format
        make lint
